
import java.io.*;
import java.util.ArrayList;
import java.util.Comparator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author user
 */
public class ShowContactsPannel extends javax.swing.JFrame {

    /**
     * Creates new form ShowContactsPannel
     */
    public ShowContactsPannel() {
        this.setTitle("AddressBook Application");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressBookLabel = new javax.swing.JLabel();
        EditContactlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowPannelArea = new javax.swing.JTextArea();
        BackButton = new javax.swing.JButton();
        Refreshbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddressBookLabel.setBackground(new java.awt.Color(102, 255, 204));
        AddressBookLabel.setFont(new java.awt.Font("hooge 05_53", 2, 14)); // NOI18N
        AddressBookLabel.setForeground(new java.awt.Color(0, 102, 102));
        AddressBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressBookLabel.setText(" AddressBook Application");

        EditContactlabel.setBackground(new java.awt.Color(255, 255, 204));
        EditContactlabel.setFont(new java.awt.Font("hooge 05_53", 1, 14)); // NOI18N
        EditContactlabel.setForeground(new java.awt.Color(0, 102, 102));
        EditContactlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditContactlabel.setText("Saved Contacts");

        ShowPannelArea.setColumns(20);
        ShowPannelArea.setRows(5);
        jScrollPane1.setViewportView(ShowPannelArea);

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Refreshbtn.setBackground(new java.awt.Color(51, 255, 102));
        Refreshbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Refreshbtn.setForeground(new java.awt.Color(51, 51, 51));
        Refreshbtn.setText("Refresh");
        Refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(EditContactlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(AddressBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Refreshbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(BackButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                        .addComponent(jScrollPane1))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AddressBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditContactlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Refreshbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BackButton)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        new UserPanel().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void RefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnActionPerformed
        ShowPannelArea.setText("");
        ArrayList<Details> list = new ArrayList<Details>();
        try {

            FileReader fr = new FileReader("Files/Contacts.txt");
            BufferedReader r = new BufferedReader(fr);

            File sortedFile = new File("Files/SortedContacts.txt");
            FileWriter w = new FileWriter(sortedFile);

            String line;
            while ((line = r.readLine()) != null) {
                String[] lpart = line.split(" ");
                Details d1 = new Details(lpart[0], lpart[1], lpart[2], lpart[3]);
                list.add(d1);

            }
            list.sort(new Comparator<Details>() {
                @Override
                public int compare(Details name1, Details name2) {
                    String n1 = name1.name;
                    String n2 = name2.name;
                    return n1.compareTo(n2);
                }
            });
            ShowPannelArea.append("Name\t\tPhone\t\tEmail\t\tAddress\n");
            for (Details l : list) {
                w.write(l.name + " " + l.phone + " " + l.email + " " + l.address + "\n");
                ShowPannelArea.append(l.name + "\t\t" + l.phone + "\t\t" + l.email + "\t\t" + l.address + "\n");
            }
            r.close();
            w.close();

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowContactsPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowContactsPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowContactsPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowContactsPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowContactsPannel().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressBookLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel EditContactlabel;
    private javax.swing.JButton Refreshbtn;
    private javax.swing.JTextArea ShowPannelArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
