/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 * @author user
 */
public class SearchPannel extends javax.swing.JFrame {

    /**
     * Creates new form SearchPannel
     */
    public SearchPannel() {
        this.setTitle("AddressBook Application");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressBookLabel = new javax.swing.JLabel();
        SearchContactLabel = new javax.swing.JLabel();
        EnterNameLabel = new javax.swing.JLabel();
        EnterNameForSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DetailsLabel = new javax.swing.JLabel();
        EnterNumberLabel = new javax.swing.JLabel();
        EnterNumberForSearchField = new javax.swing.JTextField();
        DiscriptionOfSearch = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MenuItemOfShowContacts = new javax.swing.JMenuItem();
        MenuItemOfEditContacts = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddressBookLabel.setBackground(new java.awt.Color(102, 255, 204));
        AddressBookLabel.setFont(new java.awt.Font("hooge 05_53", 2, 14)); // NOI18N
        AddressBookLabel.setForeground(new java.awt.Color(0, 102, 102));
        AddressBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressBookLabel.setText(" AddressBook Application");

        SearchContactLabel.setFont(new java.awt.Font("hooge 05_53", 1, 14)); // NOI18N
        SearchContactLabel.setForeground(new java.awt.Color(0, 102, 102));
        SearchContactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchContactLabel.setText("Search Contacts");

        EnterNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterNameLabel.setText("Enter Name    : ");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        DetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DetailsLabel.setText("Contact Details");

        EnterNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterNumberLabel.setText("Enter Number : ");

        DiscriptionOfSearch.setForeground(new java.awt.Color(153, 153, 153));
        DiscriptionOfSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiscriptionOfSearch.setText("You can search by Name or number. You can search by both of them.");

        SearchButton.setBackground(new java.awt.Color(102, 255, 102));
        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(51, 51, 51));
        SearchButton.setText("Search ");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    SearchButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        HomeButton.setBackground(new java.awt.Color(204, 255, 204));
        HomeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        jMenu2.setBackground(new java.awt.Color(204, 255, 153));
        jMenu2.setText("Menu");

        MenuItemOfShowContacts.setText("Contacts");
        MenuItemOfShowContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemOfShowContactsActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemOfShowContacts);

        MenuItemOfEditContacts.setText("Edit Contacts");
        MenuItemOfEditContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemOfEditContactsActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemOfEditContacts);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(SearchContactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(EnterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EnterNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(EnterNameForSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EnterNumberForSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 108, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(AddressBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(HomeButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DiscriptionOfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(AddressBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(DiscriptionOfSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EnterNameLabel)
                                        .addComponent(EnterNameForSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EnterNumberLabel)
                                        .addComponent(EnterNumberForSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(DetailsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SearchButton)
                                        .addComponent(HomeButton))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemOfShowContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemOfShowContactsActionPerformed
        this.dispose();
        new ShowContactsPannel().setVisible(true);
    }//GEN-LAST:event_MenuItemOfShowContactsActionPerformed

    private void MenuItemOfEditContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemOfEditContactsActionPerformed
        this.dispose();
        new EditContactsPannel().setVisible(true);
    }//GEN-LAST:event_MenuItemOfEditContactsActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        this.dispose();
        new UserPanel().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        jTextArea1.setText("");
        String name = EnterNameForSearchField.getText();
        String number = EnterNumberForSearchField.getText();
        FileReader fr = new FileReader("Files/SortedContacts.txt");
        BufferedReader reader = new BufferedReader(fr);
        String line;
        boolean found = false;
        jTextArea1.append("Name\tPhone\tEmail\tAddress\n");
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(" ");
            if (parts[0].equals(name) || parts[1].equals(number)) {
                jTextArea1.append(parts[0] + "\t" + parts[1] + "\t" + parts[2] + "\t" + parts[3] + "\n");
                found = true;
            }
        }
        if (!found) {
            jTextArea1.setText("");
            jTextArea1.append("No contacts found\n");
        }
        reader.close();
        EnterNameForSearchField.setText("");
        EnterNumberForSearchField.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressBookLabel;
    private javax.swing.JLabel DetailsLabel;
    private javax.swing.JLabel DiscriptionOfSearch;
    private javax.swing.JTextField EnterNameForSearchField;
    private javax.swing.JLabel EnterNameLabel;
    private javax.swing.JTextField EnterNumberForSearchField;
    private javax.swing.JLabel EnterNumberLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JMenuItem MenuItemOfEditContacts;
    private javax.swing.JMenuItem MenuItemOfShowContacts;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel SearchContactLabel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
